"use client"

import { AppShell } from "@/components/app-shell"
import { PageHeader } from "@/components/page-header"
import { StatCard } from "@/components/stat-card"
import { Button } from "@/components/ui/button"
import { Badge } from "@/components/ui/badge"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Progress } from "@/components/ui/progress"
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table"
import { AiRecommendations } from "@/components/ai-recommendations"
import { inventoryRows, kpis, formatCurrency } from "@/lib/data"
import { cn } from "@/lib/utils"
import { DollarSign, BedDouble, Percent, ArrowUpRight, ArrowDownRight, RefreshCw, Filter } from "lucide-react"

export default function RevenueManagementPage() {
  const totalImpact = inventoryRows.reduce((s, r) => s + r.impact, 0)

  return (
    <AppShell>
      <PageHeader title="Revenue Management" description="Room inventory, rates and AI-recommended adjustments by date">
        <Button variant="outline" size="sm" className="gap-2 bg-transparent">
          <Filter className="size-4" /> Filters
        </Button>
        <Button size="sm" className="gap-2">
          <RefreshCw className="size-4" /> Sync rates
        </Button>
      </PageHeader>

      <div className="grid grid-cols-2 gap-4 lg:grid-cols-4">
        <StatCard label="RevPAR" value="250" delta={kpis.revparDelta} icon={BedDouble} accent />
        <StatCard label="ADR" value="250" delta={kpis.adrDelta} icon={DollarSign} />
        <StatCard label="Occupancy" value={`${kpis.occupancy}%`} delta={kpis.occupancyDelta} icon={Percent} />
        <StatCard label="Projected Uplift" value={formatCurrency(totalImpact)} hint="If all recommendations applied" icon={ArrowUpRight} accent />
      </div>

      <div className="mt-6 grid grid-cols-1 gap-4 xl:grid-cols-3">
        <Card className="xl:col-span-2">
          <CardHeader>
            <CardTitle className="text-base">Inventory & Rate Optimization</CardTitle>
            <CardDescription>Next 14 days · recommended rates generated by RevPilot AI</CardDescription>
          </CardHeader>
          <CardContent className="px-0">
            <div className="overflow-x-auto">
              <Table>
                <TableHeader>
                  <TableRow className="hover:bg-transparent">
                    <TableHead className="pl-6">Date</TableHead>
                    <TableHead>Occupancy</TableHead>
                    <TableHead className="text-right">Current</TableHead>
                    <TableHead className="text-right">Recommended</TableHead>
                    <TableHead className="text-right">Revenue Impact</TableHead>
                    <TableHead className="pr-6 text-right">Confidence</TableHead>
                  </TableRow>
                </TableHeader>
                <TableBody>
                  {inventoryRows.map((row) => {
                    const up = row.recommended >= row.current
                    return (
                      <TableRow key={row.date}>
                        <TableCell className="pl-6 font-medium whitespace-nowrap">{row.date}</TableCell>
                        <TableCell>
                          <div className="flex items-center gap-2">
                            <Progress value={row.occupancy} className="h-1.5 w-16" />
                            <span className="text-xs tabular-nums text-muted-foreground">{row.occupancy}%</span>
                          </div>
                        </TableCell>
                        <TableCell className="text-right tabular-nums text-muted-foreground">${row.current}</TableCell>
                        <TableCell className="text-right">
                          <span className={cn("inline-flex items-center gap-1 font-medium tabular-nums", up ? "text-success" : "text-destructive")}>
                            {up ? <ArrowUpRight className="size-3" /> : <ArrowDownRight className="size-3" />}
                            ${row.recommended}
                          </span>
                        </TableCell>
                        <TableCell className={cn("text-right font-medium tabular-nums", row.impact >= 0 ? "text-success" : "text-destructive")}>
                          {row.impact >= 0 ? "+" : ""}{formatCurrency(row.impact)}
                        </TableCell>
                        <TableCell className="pr-6 text-right">
                          <Badge variant="secondary" className="tabular-nums">{row.confidence}%</Badge>
                        </TableCell>
                      </TableRow>
                    )
                  })}
                </TableBody>
              </Table>
            </div>
          </CardContent>
        </Card>

        <AiRecommendations />
      </div>
    </AppShell>
  )
}
